const dayDashboardHeader = [
  { text: 'Game', value: 'Game', width: 150, class: 'font-weight-medium' },
  { text: 'Ngày', value: 'Date', width: 100, class: 'font-weight-medium', align: 'center' },
  { text: 'Facebook Cost', value: 'cost1', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Apple Search', value: 'cost2', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Awords Cost', value: 'cost3', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Q.C Unity Ads', value: 'cost4', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Applovin Cost', value: 'cost5', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Ironsrc', value: 'cost6', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Apple Ads', value: 'cost7', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Vungle', value: 'cost8', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Liftoff', value: 'cost9', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Mobvista', value: 'cost10', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Yeahmobi', value: 'cost11', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Youappi', value: 'cost12', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Adcolony', value: 'cost13', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Mintegral', value: 'cost14', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Snapchat', value: 'cost15', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Personaly', value: 'cost16', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Tiktok', value: 'cost17', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Optimise', value: 'cost18', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Moloco', value: 'cost19', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Other 7', value: 'cost20', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Other 8', value: 'cost21', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Other 9', value: 'cost22', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Other 10', value: 'cost23', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Mobwonder', value: 'cost24', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Unity Video', value: 'rev1', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Vungle Video', value: 'rev2', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Applovin Video', value: 'rev3', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Admob Video', value: 'rev4', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Ironsrc Video', value: 'rev5', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'FANs Video', value: 'rev6', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Adcolony Video', value: 'rev7', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Pokkt Video', value: 'rev8', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Mintegral Video', value: 'rev9', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Pangle', value: 'rev10', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Other 4', value: 'rev11', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Other 5', value: 'rev12', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Unity Inter', value: 'rev13', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Vungle Inter', value: 'rev14', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Applovin Inter', value: 'rev15', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Admob Inter', value: 'rev16', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Ironsrc Inter', value: 'rev17', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'FANs Inter', value: 'rev18', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Adcolony Inter', value: 'rev19', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Mintegral Inter', value: 'rev20', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Banner', value: 'rev21', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Other 8', value: 'rev22', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Other 9', value: 'rev23', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Other 10', value: 'rev24', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Inapp', value: 'rev25', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
]

const weekDashboardHeader = [
  { text: 'Game', value: 'Game', width: 150, class: 'font-weight-medium' },
  { text: 'Tuần', value: '_id.year', width: 100, align: 'center', class: 'font-weight-medium' },
  { text: 'Facebook Cost', value: 'cost1', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Apple Search', value: 'cost2', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Awords Cost', value: 'cost3', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Q.C Unity Ads', value: 'cost4', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Applovin Cost', value: 'cost5', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Ironsrc', value: 'cost6', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Apple Ads', value: 'cost7', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Vungle', value: 'cost8', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Liftoff', value: 'cost9', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Mobvista', value: 'cost10', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Yeahmobi', value: 'cost11', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Youappi', value: 'cost12', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Adcolony', value: 'cost13', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Mintegral', value: 'cost14', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Snapchat', value: 'cost15', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Personaly', value: 'cost16', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Tiktok', value: 'cost17', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Optimise', value: 'cost18', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Moloco', value: 'cost19', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Other 7', value: 'cost20', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Other 8', value: 'cost21', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Other 9', value: 'cost22', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Other 10', value: 'cost23', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Mobwonder', value: 'cost24', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Unity Video', value: 'rev1', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Vungle Video', value: 'rev2', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Applovin Video', value: 'rev3', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Admob Video', value: 'rev4', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Ironsrc Video', value: 'rev5', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'FANs Video', value: 'rev6', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Adcolony Video', value: 'rev7', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Pokkt Video', value: 'rev8', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Mintegral Video', value: 'rev9', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Pangle', value: 'rev10', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Other 4', value: 'rev11', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Other 5', value: 'rev12', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Unity Inter', value: 'rev13', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Vungle Inter', value: 'rev14', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Applovin Inter', value: 'rev15', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Admob Inter', value: 'rev16', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Ironsrc Inter', value: 'rev17', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'FANs Inter', value: 'rev18', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Adcolony Inter', value: 'rev19', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Mintegral Inter', value: 'rev20', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Banner', value: 'rev21', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Other 8', value: 'rev22', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Other 9', value: 'rev23', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Other 10', value: 'rev24', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Inapp', value: 'rev25', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
]

const monthDashboardHeader = [
  { text: 'Game', value: 'Game', width: 150, class: 'font-weight-medium' },
  { text: 'Tháng', value: '_id.year', width: 150, align: 'center', class: 'font-weight-medium' },
  { text: 'Facebook Cost', value: 'cost1', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Apple Search', value: 'cost2', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Awords Cost', value: 'cost3', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Q.C Unity Ads', value: 'cost4', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Applovin Cost', value: 'cost5', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Ironsrc', value: 'cost6', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Apple Ads', value: 'cost7', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Vungle', value: 'cost8', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Liftoff', value: 'cost9', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Mobvista', value: 'cost10', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Yeahmobi', value: 'cost11', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Youappi', value: 'cost12', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Adcolony', value: 'cost13', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Mintegral', value: 'cost14', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Snapchat', value: 'cost15', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Personaly', value: 'cost16', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Tiktok', value: 'cost17', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Optimise', value: 'cost18', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Moloco', value: 'cost19', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Other 7', value: 'cost20', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Other 8', value: 'cost21', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Other 9', value: 'cost22', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Other 10', value: 'cost23', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Mobwonder', value: 'cost24', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Unity Video', value: 'rev1', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Vungle Video', value: 'rev2', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Applovin Video', value: 'rev3', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Admob Video', value: 'rev4', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Ironsrc Video', value: 'rev5', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'FANs Video', value: 'rev6', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Adcolony Video', value: 'rev7', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Pokkt Video', value: 'rev8', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Mintegral Video', value: 'rev9', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Pangle', value: 'rev10', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Other 4', value: 'rev11', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Other 5', value: 'rev12', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Unity Inter', value: 'rev13', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Vungle Inter', value: 'rev14', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Applovin Inter', value: 'rev15', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Admob Inter', value: 'rev16', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Ironsrc Inter', value: 'rev17', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'FANs Inter', value: 'rev18', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Adcolony Inter', value: 'rev19', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Mintegral Inter', value: 'rev20', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Banner', value: 'rev21', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Other 8', value: 'rev22', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Other 9', value: 'rev23', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Other 10', value: 'rev24', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Inapp', value: 'rev25', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
]

const quarterDashboardHeader = [
  { text: 'Game', value: 'Game', width: 150, class: 'font-weight-medium' },
  { text: 'Quý', value: '_id.quarter', width: 100, sortable: false, align: 'center', class: 'font-weight-medium' },
  { text: 'Facebook Cost', value: 'cost1', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Apple Search', value: 'cost2', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Awords Cost', value: 'cost3', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Q.C Unity Ads', value: 'cost4', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Applovin Cost', value: 'cost5', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Ironsrc', value: 'cost6', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Apple Ads', value: 'cost7', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Vungle', value: 'cost8', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Liftoff', value: 'cost9', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Mobvista', value: 'cost10', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Yeahmobi', value: 'cost11', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Youappi', value: 'cost12', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Adcolony', value: 'cost13', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Mintegral', value: 'cost14', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Snapchat', value: 'cost15', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Personaly', value: 'cost16', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Tiktok', value: 'cost17', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Optimise', value: 'cost18', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Moloco', value: 'cost19', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Other 7', value: 'cost20', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Other 8', value: 'cost21', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Other 9', value: 'cost22', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Other 10', value: 'cost23', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Mobwonder', value: 'cost24', sortable: false, align: 'center', width: 100, class: 'font-weight-medium light-blue lighten-4' },
  { text: 'Unity Video', value: 'rev1', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Vungle Video', value: 'rev2', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Applovin Video', value: 'rev3', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Admob Video', value: 'rev4', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Ironsrc Video', value: 'rev5', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'FANs Video', value: 'rev6', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Adcolony Video', value: 'rev7', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Pokkt Video', value: 'rev8', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Mintegral Video', value: 'rev9', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Pangle', value: 'rev10', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Other 4', value: 'rev11', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Other 5', value: 'rev12', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Unity Inter', value: 'rev13', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Vungle Inter', value: 'rev14', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Applovin Inter', value: 'rev15', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Admob Inter', value: 'rev16', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Ironsrc Inter', value: 'rev17', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'FANs Inter', value: 'rev18', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Adcolony Inter', value: 'rev19', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Mintegral Inter', value: 'rev20', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Banner', value: 'rev21', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Other 8', value: 'rev22', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Other 9', value: 'rev23', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Other 10', value: 'rev24', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
  { text: 'Inapp', value: 'rev25', sortable: false, align: 'center', width: 100, class: 'font-weight-medium amber lighten-3' },
]

const costItems = [
  'Facebook Cost',
  'Apple Search',
  'Awords Cost',
  'Q.C Unity Ads',
  'Applovin Cost',
  'Ironsrc',
  'Apple Ads',
  'Vungle',
  'Liftoff',
  'Mobvista',
  'Yeahmobi',
  'Youappi',
  'Adcolony',
  'Mintegral',
  'Snapchat',
  'Personaly',
  'Tiktok',
  'Optimise',
  'Moloco',
  'Other 7',
  'Other 8',
  'Other 10',
  'Mobwonder',
]

const revItems = [
  'Unity Video',
  'Vungle Video',
  'Applovin Video',
  'Admob Video',
  'Ironsrc Video',
  'FANs Video',
  'Adcolony Video',
  'Pokkt Video',
  'Mintegral Video',
  'Pangle',
  'Other 4',
  'Other 5',
  'Unity Inter',
  'Vungle Inter',
  'Applovin Inter',
  'Admob Inter',
  'Ironsrc Inter',
  'FANs Inter',
  'Adcolony Inter',
  'Mintegral Inter',
  'Banner',
  'Other 8',
  'Other 9',
  'Other 10',
  'Inapp',
]

export default {
  dayDashboardHeader: dayDashboardHeader,
  weekDashboardHeader: weekDashboardHeader,
  monthDashboardHeader: monthDashboardHeader,
  quarterDashboardHeader: quarterDashboardHeader,
  costItems: costItems,
  revItems: revItems,
}
